// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Models
{
    [Table("userdb")]
    public partial class Userdb
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("email")]

        public string Email { get; set; }
        [Required]
        [Column("password")]
 
        public string Password { get; set; }
        [Required]
        [Column("role")]
  
        public string Role { get; set; }
        [Column("uniqueStoreId")]
        public int UniqueStoreId { get; set; }
    }
}